### ISSUE TITLE
swr如何把app.ts的getuserinfo延迟到layout?

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/spirit-admin#1]
https://github.com/linxianxi/spirit-admin/blob/master/src/App.tsx#L13

我用swr
```
import useSWR from "swr";
import { myFetch } from "./../../fetch";


export const useUser = () => {
  const token = localStorage.getItem("token") || "";
  const { data, error, isLoading, mutate } = useSWR(
    token ? `/api/me` : null,
    myFetch
  );

  return {
    user: data?.data,
    isLoading,
    isError: error,
    mutate,
  };
};
```

swr升级到2.0了, 多了useSWRMutation ,但是这玩意纯手动
如果要使用useSwr 封装useUser, 我得把enable条件内置到他的key里, 比如` token ? `/api/me` : null,`但是没办法有更多的灵活性,比如依赖组件里的state,所以swr 最好不要封useUser, 而是直接传递key,和fetch吗?

方法1: 
```app.tsx
// 直接这样用
const {data} = uswSwr('/api/me',myFetch)
// 不能这样 
const {data} = uswUser()
```
方法二, 
得放弃使用useSwr, 改成直接使用useSWRMutation 来获取用户信息? 这样应该就可以封装了

你有什么想法吗

**Comment by linxianxi** [comment]
url 应该就是 key，为null就取不到了，swr 不怎么用，都是用react-query。第二种就是手动获取完再存到状态管理里共享也可以

**Comment by Valar103769** [comment]
嗯, 但是我感觉在管理系统里并不好使用react-query啊, 比如查询列表,一般都要好多筛选器,这个key就复杂了啊,要在其他组件使用查询结构,还得把key传下去

**Comment by linxianxi** [comment]
key 直接一个就行了，["productList"]，筛选器没必要写进去。
