### ISSUE TITLE
npx degit linxianxi/spirit-admin my-project

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/spirit-admin#2]
貌似应该使用 `npx degit linxianxi/spirit-admin my-project` 下载这种模板项目,

直接使用git clone 会关联到你的仓库,如果使用 --depth 参数克隆的,删除远程关联还有点小麻烦

**Comment by linxianxi** [comment]
可以 clone 下来之后删掉 .git，再重新连接一个新的远程仓库
