### ISSUE TITLE
使用了react-query的isLoading等状态, 就会导致组件重新渲染, 这个问题需要解决吗?

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/spirit-admin#3]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/36926073/209121801-86c8c4e2-c6f3-42fa-98d4-cc8a7edde3c9.png">

**Comment by linxianxi** [comment]
这个相当于 state 啊，变化了肯定会渲染
