### ISSUE TITLE
多个路由使用同一个组件, 怎么加key? 

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/spirit-admin#5]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/36926073/210522246-d118bda2-4938-4a6a-aea1-223e59793a92.png">

tsx文件里用不了useHook, 有啥其他办法吗?

**Comment by linxianxi** [comment]
你加 key 干什么？

**Comment by Valar103769** [comment]
:params 动态路由, 使用同一个Report组件, 切换路由时,组件状态不会重置, 只要只用params的,都会遇到这个问题的
我解决了, 搞了个中间页面,在中间页里使用location 注入key
