### ISSUE TITLE
只想点击查询安妮呢才请求数据,怎么使用react-query? 

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/spirit-admin#6]
不会执行,这哪里写的有问题吗?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/36926073/211526287-eaf2bd9d-8827-43d0-86f5-e0858dfeb195.png">

**Comment by linxianxi** [comment]
react-query 的使用问题你在这里提 issue 干嘛。

useQuery 的 enable 可以控制，或者使用 useMutation。
